---
- hosts: tag_Name_wom2_api:&key_wom
  become: true
  tasks:
  - name: Update package list
    apt: update_cache=yes cache_valid_time=36000
  - name: Install base packages
    apt: name={{item}} state=present
    with_items:
      - python-pip
      - python-dev
  - name: Install uwsgi and flask for python
    pip: name={{item}} state=present
    with_items:
      - prometheus_client
      - flask
      - tornado
      - requests
  - name: Clone flask-kube-prometheus project to private node
    git:
      repo: https://github.com/InsightDataScience/flask-kube-prometheus.git
      dest: /home/ubuntu
  - name: Copy fkp service to init.d
    copy:
      src: templates/etc/init.d/fkp
      dest: /etc/init.d/fkp
  - name: Make fkp service executable
    file:
      path: /etc/init.d/fkp
      mode: 0755
  - name: Start API server
    service:
      name: fkp
      state: restarted
